---
title: ""
---

<br>

#### About

[Department of Epidemiology](http://www.mailman.columbia.edu/academic-departments/epidemiology)  
[Columbia Mailman School of Public Health](http://www.mailman.columbia.edu/)

I received a BS in Biology from [Fordham University](http://www.fordham.edu) in 2015 and a MPH in Epidemiology from [COlumbia University](http://www.mailman.columbia.edu/academic-departments/epidemiology) in 2019.


As a recent Epidemiology MPH graduate from the Columbia University Mailman School of Public Health I have experience in data analysis, R, SAS, and epidemiological methods as well as a strong interest in evidence-based medicine. With these qualifications, I believe I am a strong fit for this opportunity and would be honored to be considered.

My data analysis and epidemiology skills have been honed over the previous two years while attending Columbia University. My relevant coursework at the Mailman School of Public Health included two semesters of applied regression, analysis of categorical data, two semesters of data science, statistical analysis in SAS, and a variety of epidemiology courses. I was able to utilize skills and knowledge from these courses in my prior internship at the New York City Department of Health and Mental Hygiene. In this role, I used data analysis and biostatistics techniques including multivariable linear regression analysis and analysis of categorical data, and programmed extensively in SAS in order to conduct an exploratory analysis of diabetes in the New York City Tuberculosis population. This analysis was conducted on electronic medical record data in a dataset of over 5,000 records. I was also able to apply skills from my courses at my internship at EcoHealth Alliance, where I gathered and cleaned data, and conducted multivariable regression and geospatial analysis on malaria incidence in Malaysia using R. The data used in this project was reused for my Master’s thesis where I built a predictive model in R using GAMs to better understand which environmental and social factors were most important when predicting Malaria incidence.

Prior to attending graduate school, I gained significant clinical research experience working as a research assistant at Beth Israel Deaconess Medical Center for Dr. Ciaran Kelly. In this role I served as a research coordinator for an NIH R01 funded study and was responsible for building a database of all enrolled patients and their pertinent electronic medical record data as well as maintaining data integrity for the database. This role required me to work in a team environment, with weekly meetings to discuss progress and to set goals. 

I look forward to the opportunity to meet with you and discuss how my education credentials and experience can contribute to the health services, decision analysis, and clinical epidemiology research 
